version: "3.8"

services:
  db:
    image: postgres:12.2-alpine
    container_name: "comments-database"
    ports:
      - "5432:5432"
    env_file:
      - .postgres.env
    networks:
      - fullstack
    volumes:
      - database_postgres:/var/lib/postgresql/data
  api:
    build: .
    container_name: "comments-rest-api"
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - fullstack

volumes:
  database_postgres:

networks:
  fullstack:
    driver: bridge
